workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    vercel-OAS:
        inputs:
            - location: https://openapi.vercel.sh/
        overlays:
            - location: ../../overlay.yaml
        ruleset: vercelRestAPIRuleset
        registry:
            location: registry.speakeasyapi.dev/vercel-nv/vercel/vercel-oas
targets:
    vercel:
        target: typescript
        source: vercel-OAS
        publish:
            npm:
                token: $npm_token
